exception Backtrace_or_exception.Exn
Raised at Backtrace_or_exception.without_reraise in file "backtrace_or_exception.ml", line 13, characters 47-56
Called from Backtrace_or_exception.run in file "backtrace_or_exception.ml", line 29, characters 6-10
---------------------------
exception Backtrace_or_exception.Exn
Raised at Backtrace_or_exception.without_reraise in file "backtrace_or_exception.ml", line 13, characters 47-56
Called from Backtrace_or_exception.run in file "backtrace_or_exception.ml", line 29, characters 6-10
Re-raised at Backtrace_or_exception.return_exn in file "backtrace_or_exception.ml", line 8, characters 27-36
Called from Backtrace_or_exception.return_exn in file "backtrace_or_exception.ml" (inlined), lines 7-8, characters 15-93
Called from Backtrace_or_exception.with_reraise in file "backtrace_or_exception.ml", line 17, characters 8-44
Re-raised at Backtrace_or_exception.with_reraise in file "backtrace_or_exception.ml", line 18, characters 47-56
Called from Backtrace_or_exception.run in file "backtrace_or_exception.ml", line 29, characters 6-10
---------------------------
exception Backtrace_or_exception.Exn
Raised at Backtrace_or_exception.trickier in file "backtrace_or_exception.ml", line 25, characters 49-58
Called from Backtrace_or_exception.run in file "backtrace_or_exception.ml", line 29, characters 6-10
---------------------------
